name: install-pip-deps
description: Clone python-greetings repo and install Python dependencies

runs:
  using: composite
  steps:
    - name: Print stage info
      shell: cmd
      run: echo Installing all required dependencies...

    - name: Clone python-greetings repository
      uses: actions/checkout@v4
      with:
        repository: mtararujs/python-greetings
        path: python-greetings

    - name: Create virtual environment
      shell: cmd
      working-directory: python-greetings
      run: python -m venv venv

    - name: Install Python dependencies
      shell: cmd
      working-directory: python-greetings
      run: venv\Scripts\python.exe -m pip install -r requirements.txt
