name: Python Greetings Pipeline

on:
  workflow_dispatch:

jobs:
  install-pip-deps:
    runs-on: self-hosted
    steps:
      - name: Prepare python-greetings source
        shell: cmd
        run: |
          if exist C:\deployments\python-greetings-base rmdir /s /q C:\deployments\python-greetings-base
          git clone https://github.com/mtararujs/python-greetings.git C:\deployments\python-greetings-base

      - name: Create virtual environment
        shell: cmd
        working-directory: C:\deployments\python-greetings-base
        run: python -m venv venv

      - name: Install Python dependencies
        shell: cmd
        working-directory: C:\deployments\python-greetings-base
        run: venv\Scripts\python.exe -m pip install -r requirements.txt

  deploy-to-dev:
    runs-on: self-hosted
    needs: install-pip-deps
    steps:
      - name: Stop old PM2 process if it exists
        shell: cmd
        run: pm2 delete greetings-app-dev & set "errorlevel=0"

      - name: Prepare dev deployment folder
        shell: cmd
        run: |
          if exist C:\deployments\python-greetings-dev rmdir /s /q C:\deployments\python-greetings-dev
          git clone https://github.com/mtararujs/python-greetings.git C:\deployments\python-greetings-dev

      - name: Create virtual environment
        shell: cmd
        working-directory: C:\deployments\python-greetings-dev
        run: python -m venv venv

      - name: Install Python dependencies
        shell: cmd
        working-directory: C:\deployments\python-greetings-dev
        run: venv\Scripts\python.exe -m pip install -r requirements.txt

      - name: Start application with PM2
        shell: cmd
        working-directory: C:\deployments\python-greetings-dev
        run: pm2 start app.py --name greetings-app-dev --interpreter "C:\deployments\python-greetings-dev\venv\Scripts\python.exe" -- --port 7001

      - name: Wait for app to start
        shell: cmd
        run: ping 127.0.0.1 -n 6 > nul

      - name: Show PM2 list
        shell: cmd
        run: pm2 list

  tests-on-dev:
    runs-on: self-hosted
    needs: deploy-to-dev
    steps:
      - name: Prepare API test repository
        shell: cmd
        run: |
          if exist C:\deployments\course-js-api-framework rmdir /s /q C:\deployments\course-js-api-framework
          git clone https://github.com/mtararujs/course-js-api-framework.git C:\deployments\course-js-api-framework

      - name: Install Node dependencies
        shell: cmd
        working-directory: C:\deployments\course-js-api-framework
        run: npm install

      - name: Run greetings tests on dev
        shell: cmd
        working-directory: C:\deployments\course-js-api-framework
        run: npm run greetings greetings_dev

  deploy-to-stg:
    runs-on: self-hosted
    needs: tests-on-dev
    steps:
      - name: Stop old PM2 process if it exists
        shell: cmd
        run: pm2 delete greetings-app-stg & set "errorlevel=0"

      - name: Prepare stg deployment folder
        shell: cmd
        run: |
          if exist C:\deployments\python-greetings-stg rmdir /s /q C:\deployments\python-greetings-stg
          git clone https://github.com/mtararujs/python-greetings.git C:\deployments\python-greetings-stg

      - name: Create virtual environment
        shell: cmd
        working-directory: C:\deployments\python-greetings-stg
        run: python -m venv venv

      - name: Install Python dependencies
        shell: cmd
        working-directory: C:\deployments\python-greetings-stg
        run: venv\Scripts\python.exe -m pip install -r requirements.txt

      - name: Start application with PM2
        shell: cmd
        working-directory: C:\deployments\python-greetings-stg
        run: pm2 start app.py --name greetings-app-stg --interpreter "C:\deployments\python-greetings-stg\venv\Scripts\python.exe" -- --port 7002

      - name: Wait for app to start
        shell: cmd
        run: ping 127.0.0.1 -n 6 > nul

      - name: Show PM2 list
        shell: cmd
        run: pm2 list

  tests-on-stg:
    runs-on: self-hosted
    needs: deploy-to-stg
    steps:
      - name: Prepare API test repository
        shell: cmd
        run: |
          if exist C:\deployments\course-js-api-framework rmdir /s /q C:\deployments\course-js-api-framework
          git clone https://github.com/mtararujs/course-js-api-framework.git C:\deployments\course-js-api-framework

      - name: Install Node dependencies
        shell: cmd
        working-directory: C:\deployments\course-js-api-framework
        run: npm install

      - name: Run greetings tests on stg
        shell: cmd
        working-directory: C:\deployments\course-js-api-framework
        run: npm run greetings greetings_stg

  deploy-to-preprod:
    runs-on: self-hosted
    needs: tests-on-stg
    steps:
      - name: Stop old PM2 process if it exists
        shell: cmd
        run: pm2 delete greetings-app-preprod & set "errorlevel=0"

      - name: Prepare preprod deployment folder
        shell: cmd
        run: |
          if exist C:\deployments\python-greetings-preprod rmdir /s /q C:\deployments\python-greetings-preprod
          git clone https://github.com/mtararujs/python-greetings.git C:\deployments\python-greetings-preprod

      - name: Create virtual environment
        shell: cmd
        working-directory: C:\deployments\python-greetings-preprod
        run: python -m venv venv

      - name: Install Python dependencies
        shell: cmd
        working-directory: C:\deployments\python-greetings-preprod
        run: venv\Scripts\python.exe -m pip install -r requirements.txt

      - name: Start application with PM2
        shell: cmd
        working-directory: C:\deployments\python-greetings-preprod
        run: pm2 start app.py --name greetings-app-preprod --interpreter "C:\deployments\python-greetings-preprod\venv\Scripts\python.exe" -- --port 7003

      - name: Wait for app to start
        shell: cmd
        run: ping 127.0.0.1 -n 6 > nul

      - name: Show PM2 list
        shell: cmd
        run: pm2 list

  tests-on-preprod:
    runs-on: self-hosted
    needs: deploy-to-preprod
    steps:
      - name: Prepare API test repository
        shell: cmd
        run: |
          if exist C:\deployments\course-js-api-framework rmdir /s /q C:\deployments\course-js-api-framework
          git clone https://github.com/mtararujs/course-js-api-framework.git C:\deployments\course-js-api-framework

      - name: Install Node dependencies
        shell: cmd
        working-directory: C:\deployments\course-js-api-framework
        run: npm install

      - name: Run greetings tests on preprod
        shell: cmd
        working-directory: C:\deployments\course-js-api-framework
        run: npm run greetings greetings_preprod

  deploy-to-prod:
    runs-on: self-hosted
    needs: tests-on-preprod
    steps:
      - name: Stop old PM2 process if it exists
        shell: cmd
        run: pm2 delete greetings-app-prod & set "errorlevel=0"

      - name: Prepare prod deployment folder
        shell: cmd
        run: |
          if exist C:\deployments\python-greetings-prod rmdir /s /q C:\deployments\python-greetings-prod
          git clone https://github.com/mtararujs/python-greetings.git C:\deployments\python-greetings-prod

      - name: Create virtual environment
        shell: cmd
        working-directory: C:\deployments\python-greetings-prod
        run: python -m venv venv

      - name: Install Python dependencies
        shell: cmd
        working-directory: C:\deployments\python-greetings-prod
        run: venv\Scripts\python.exe -m pip install -r requirements.txt

      - name: Start application with PM2
        shell: cmd
        working-directory: C:\deployments\python-greetings-prod
        run: pm2 start app.py --name greetings-app-prod --interpreter "C:\deployments\python-greetings-prod\venv\Scripts\python.exe" -- --port 7004

      - name: Wait for app to start
        shell: cmd
        run: ping 127.0.0.1 -n 6 > nul

      - name: Show PM2 list
        shell: cmd
        run: pm2 list

  tests-on-prod:
    runs-on: self-hosted
    needs: deploy-to-prod
    steps:
      - name: Prepare API test repository
        shell: cmd
        run: |
          if exist C:\deployments\course-js-api-framework rmdir /s /q C:\deployments\course-js-api-framework
          git clone https://github.com/mtararujs/course-js-api-framework.git C:\deployments\course-js-api-framework

      - name: Install Node dependencies
        shell: cmd
        working-directory: C:\deployments\course-js-api-framework
        run: npm install

      - name: Run greetings tests on prod
        shell: cmd
        working-directory: C:\deployments\course-js-api-framework
        run: npm run greetings greetings_prod
